version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5455:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - dev

  test-db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - dev

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - dev
    command: ["redis-server", "--appendonly", "yes"]

networks:
  dev: